Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ThongTinYTe.CovidVnServices.Interfaces;
using ThongTinYTe.CovidVnServices.Models;
using ThongTinYTe.Models;

namespace ThongTinYTe.Controllers
{
    public class CaseController : Controller
    {
        private readonly ICovidVnDetailsService _service_detail = null;
        private readonly ICovidVnService _service = null;
        public CaseController(ICovidVnService service, ICovidVnDetailsService service_detail)
        {
            this._service = service;
            this._service_detail = service_detail;
        }

        // public IActionResult Index() {
        //     return View(_service_detail.GetRecords());
        // }

        public async Task<IActionResult> KhaiBaoToanDan()
        {
            // Lấy danh sách thành phố ở Việt Nam từ service
            IEnumerable<ProvinceRecord> records = _service.GetRecords();
            List<string> city_list = new List<string>();
            foreach (ProvinceRecord record in records)
            {
                city_list.Add(record.Province);
            }
            ViewBag.cities = city_list;

            // Lấy danh sách quốc gia từ api
            HttpClient client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            string countries_api = "https://restcountries.eu/rest/v2/all";
            HttpResponseMessage response_countries_api = await client.GetAsync(countries_api);
            string raw_cities = await response_countries_api.Content.ReadAsStringAsync();
            List<CountriesAPI> countries_object = JsonConvert.DeserializeObject<List<CountriesAPI>>(raw_cities);
            List<string> countries_list = new List<string>();
            foreach (var country in countries_object)
            {
                countries_list.Add(country.name);
            }
            ViewBag.countries = countries_list;

            return View();
        }
        [HttpPost]
        public IActionResult KhaiBaoToanDan(KhaiBaoToanDan people)
        {
            IEnumerable<CaseRecord> records = _service_detail.GetRecords();
            foreach (CaseRecord record in records)
            {
                if (record.Location == people.tinh_thanh)
                {
                    return View("CanhBaoKhuVuc");
                }
            }
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> KhaiBaoDiChuyen()
        {
            // Lấy danh sách thành phố ở Việt Nam từ service
            IEnumerable<ProvinceRecord> records = _service.GetRecords();
            List<string> city_list = new List<string>();
            foreach (ProvinceRecord record in records)
            {
                city_list.Add(record.Province);
            }
            ViewBag.cities = city_list;
            // Lấy danh sách quốc gia từ api
            HttpClient client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            string countries_api = "https://restcountries.eu/rest/v2/all";
            HttpResponseMessage response_countries_api = await client.GetAsync(countries_api);
            string raw_cities = await response_countries_api.Content.ReadAsStringAsync();
            List<CountriesAPI> countries_object = JsonConvert.DeserializeObject<List<CountriesAPI>>(raw_cities);
            List<string> countries_list = new List<string>();
            foreach (var country in countries_object)
            {
                countries_list.Add(country.name);
            }
            ViewBag.countries = countries_list; 

            return View();
        }
        [HttpPost]
        public IActionResult KhaiBaoDiChuyen(KhaiBaoDiChuyen traveler)
        {
            IEnumerable<CaseRecord> records = _service_detail.GetRecords();
            foreach (CaseRecord record in records)
            {
                if (record.Location == traveler.noi_di || record.Location == traveler.noi_den)
                {
                    return View("CanhBaoCachLy");
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
    public class CountriesAPI
    {
        public string name { get; set; }
    }
}

Controllers/ProvinceController.cs
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using ThongTinYTe.CovidVnServices.Interfaces;
using ThongTinYTe.CovidVnServices.Models;
namespace ThongTinYTe.Controllers
{
    public class ProvinceController : Controller
    {
        private readonly ICovidVnService _service = null;

        public ProvinceController(ICovidVnService service) {
            this._service = service;
        }

        public IActionResult Index() {
            List<ProvinceRecord> records = new List<ProvinceRecord>(_service.GetRecords());
            return View(records);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThongTinYTe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*Uy zone*@
    <script src="https://kit.fontawesome.com/88ef2b516b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    @*-------*@
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin="" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>
    
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-book-medical"></i> ThongTinYTe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-globe-americas"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Province" asp-action="Index"><i class="fas fa-map-marked-alt"></i> Tình hình Việt Nam</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Case" asp-action="KhaiBaoToanDan"><i class="fas fa-notes-medical"></i> Khai báo toàn dân</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Case" asp-action="KhaiBaoDiChuyen"><i class="fas fa-bus"></i> Khai báo di chuyển</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        <div class="container-fluid body-content" style="height: 20%; bottom:0;">
            &copy; @DateTime.Now.Year - ThongTinYTe
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*Uy zone*@
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    @*-------*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>